[tool.poetry]
name = "cw-4-total"
version = "0.1.0"
description = ""
authors = ["vladimirbutyrskii <vlaver@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
